spring.datasource.url = jdbc:postgresql://app-producao-postgres-ck25-wrjd.hospedagemelastica.com.br:5432/guimas-bet-prod
spring.datasource.username = qlxpxxntucfd
spring.datasource.password = btxsdwyyqqkpefggxpdfgwse
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

spring.data.mongodb.uri=mongodb://llnrndtrcaek:alapnfwetqfcosgxrgikwetw@app-producao-mongodb-xugj.hospedagemelastica.com.br:28901/nbkbpkggaquy?authSource=admin
##spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/appdb?authSource=admin

spring.datasource.hikari.validation-query=SELECT 1
spring.datasource.max-active=20
spring.datasource.max-idle=8
spring.datasource.min-idle=8
spring.datasource.initial-size=5
spring.datasource.test-on-borrow=false 

guimasnacopa.config.bolaoAtivo = copa-2026




